In [ ]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.13/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.5.0)

In [ ]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
vec_king=wv['king']

In [ ]:
import pandas as pd
messages=pd.read_csv("SMSSpamCollection.txt", sep='\t', names=["label", "message"])

In [ ]:
!pip install nltk
import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk) (3.1.2)

In [ ]:
import re
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
corpus=[]
for i in range(len(messages)):
    review=re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [ ]:
words=[]
for sent in corpus:
  sent_token=sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

In [ ]:
import gensim
model=gensim.models.Word2Vec(words)

In [ ]:
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope',
 'oh',
 'claim',
 'great',
 'hey',
 'him',
 'number',
 'give',
 'more',
 'too',
 'happy',
 'work',
 'friend',
 'wat',
 'had',
 'way',
 'yes',
 'www',
 've',
 'should',
 'let',
 'prize',
 'won',
 'right',
 'tomorrow',
 'already',
 'tone',
 'after',
 'said',
 'ask',
 'win',
 'doing',
 'amp',
 'cash',
 'life',
 'im',
 'yeah',
 'really',
 'babe',
 'why',
 'meet',
 'find',
 'them',
 'miss',
 'very',
 'morning',
 'last',
 'service',
 'year',
 'uk',
 'thanks',
 'care',
 'would',
 'anything',
 'com',
 'also',
 'nokia',
 'lol',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',
 'over',
 'something',
 'gud',
 'buy',
 'again',
 'before',
 'cant',
 'wait',
 'box',
 'place',
 'first',
 'his',
 'even',
 'guy',
 'someone',
 'help',
 'went',
 'wish',
 'nice',
 'were',
 'next',
 'tonight',
 'off',
 'show',
 'which',
 'soon',
 'word',
 'around',
 'money',
 'could',
 'customer',
 'many',
 'sleep',
 'chat',
 'late',
 'per',
 'ya',
 'sm',
 'always',
 'gonna',
 'wan',
 'leave',
 'down',
 'name',
 'lot',
 'other',
 'pm',
 'end',
 'dun',
 'told',
 'st',
 'person',
 'waiting',
 'special',
 'hello',
 'girl',
 'try',
 'fine',
 'month',
 'hour',
 'may',
 'minute',
 'coming',
 'heart',
 'haha',
 'people',
 'best',
 'th',
 'thk',
 'yet',
 'guaranteed',
 'smile',
 'same',
 'done',
 'getting',
 'god',
 'ppm',
 'thought',
 'use',
 'offer',
 'didn',
 'start',
 'holiday',
 'class',
 'stuff',
 'talk',
 'line',
 'mean',
 'bit',
 'man',
 'live',
 'car',
 'lunch',
 'cost',
 'few',
 'draw',
 'job',
 'finish',
 'problem',
 'never',
 'being',
 'plan',
 'ill',
 'house',
 'hr',
 'better',
 'cool',
 'thats',
 'meeting',
 'trying',
 'yup',
 'mind',
 'having',
 'ready',
 'dat',
 'account',
 'long',
 'pobox',
 'rate',
 'game',
 'weekend',
 'chance',
 'enjoy',
 'wk',
 'real',
 'half',
 'latest',
 'world',
 'than',
 'because',
 'sir',
 'bt',
 'guess',
 'po',
 'yo',
 'check',
 'play',
 'room',
 'pic',
 'voucher',
 'boy',
 'luv',
 'nothing',
 'wanna',
 'awarded',
 'sweet',
 'look',
 'eat',
 'camera',
 'receive',
 'lar',
 'shit',
 'big',
 'liao',
 'another',
 'into',
 'landline',
 'birthday',
 'ah',
 'dinner',
 'xxx',
 'quite',
 'ever',
 'kiss',
 'might',
 'video',
 'jus',
 'age',
 'land',
 'watch',
 'watching',
 'wont',
 'question',
 'probably',
 'orange',
 'two',
 'baby',
 'thanx',
 'called',
 'tv',
 'dream',
 'worry',
 'aight',
 'bed',
 'pa',
 'once',
 'hear',
 'nd',
 'speak',
 'fun',
 'early',
 'point',
 'princess',
 'bad',
 'den',
 'actually',
 'sat',
 'shall',
 'nite',
 'forgot',
 'part',
 'maybe',
 'ringtone',
 'doe',
 'left',
 'bus',
 'pay',
 'remember',
 'network',
 'apply',
 'office',
 'dunno',
 'made',
 'shopping',
 'reach',
 'easy',
 'between',
 'hurt',
 'code',
 'dad',
 'wife',
 'fuck',
 'put',
 'true',
 'didnt',
 'everything',
 'face',
 'leh',
 'evening',
 'little',
 'award',
 'anyway',
 'xx',
 'dis',
 'mate',
 'town',
 'gift',
 'sound',
 'working',
 'those',
 'mail',
 'yr',
 'school',
 'movie',
 'afternoon',
 'looking',
 'thank',
 'enough',
 'selected',
 'while',
 'detail',
 'asked',
 'collect',
 'tmr',
 'missing',
 'without',
 'most',
 'pound',
 'entry',
 'important',
 'hav',
 'xmas',
 'sexy',
 'join',
 'must',
 'price',
 'okay',
 'came',
 'pain',
 'since',
 'wanted',
 'valid',
 'though',
 'wif',
 'until',
 'collection',
 'bring',
 'wot',
 'book',
 'wake',
 'able',
 'til',
 'answer',
 'abt',
 'mob',
 'run',
 'missed',
 'lesson',
 'update',
 'plus',
 'away',
 'de',
 'change',
 'plz',
 'charge',
 'decimal',
 'stay',
 'juz',
 'test',
 'haven',
 'wen',
 'date',
 'colour',
 'attempt',
 'bored',
 'dude',
 'weekly',
 'music',
 'shop',
 'else',
 'havent',
 'hair',
 'double',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'online',
 'these',
 'drink',
 'friendship',
 'optout',
 'oso',
 'id',
 'coz',
 'haf',
 'top',
 'food',
 'making',
 'trip',
 'yours',
 'credit',
 'net',
 'family',
 'sch',
 'either',
 'feeling',
 'club',
 'hot',
 'gr',
 'smoke',
 'player',
 'address',
 'driving',
 'yourself',
 'delivery',
 'tried',
 'ard',
 'national',
 'sad',
 'together',
 'lose',
 'sae',
 'beautiful',
 'tot',
 'head',
 'post',
 'calling',
 'full',
 'ring',
 'wid',
 'walk',
 'both',
 'story',
 'si',
 'believe',
 'order',
 'nt',
 'busy',
 'bonus',
 'second',
 'mom',
 'http',
 'brother',
 'await',
 'drive',
 'saying',
 'mum',
 'eve',
 'poly',
 'huh',
 'chikku',
 'row',
 'happen',
 'noe',
 'sleeping',
 'hand',
 'leaving',
 'old',
 'smiling',
 'close',
 'info',
 'set',
 'drop',
 'rite',
 'email',
 'pub',
 'simple',
 'thinking',
 'suite',
 'mths',
 'okie',
 'wil',
 'awesome',
 'parent',
 'match',
 'private',
 'cause',
 'started',
 'finished',
 'took',
 'congrats',
 'tomo',
 'doesn',
 'aft',
 'news',
 'hl',
 'auction',
 'anyone',
 'neva',
 'mine',
 'gd',
 'reason',
 'valentine',
 'sister',
 'card',
 'unsubscribe',
 'angry',
 'company',
 'tc',
 'break',
 'touch',
 'content',
 'everyone',
 'taking',
 'statement',
 'forget',
 'tho',
 'caller',
 'final',
 'available',
 'alone',
 'loving',
 'gal',
 'knw',
 'sun',
 'whatever',
 'opt',
 'dating',
 'choose',
 'found',
 'worth',
 'carlos',
 'bank',
 'fancy',
 'each',
 'whats',
 'open',
 'type',
 'expires',
 'search',
 'ticket',
 'lucky',
 'treat',
 'hows',
 'party',
 'fast',
 'sub',
 'visit',
 'nyt',
 'kind',
 'welcome',
 'bout',
 'mobileupd',
 'far',
 'anytime',
 'congratulation',
 'secret',
 'gbp',
 'exam',
 'college',
 'boytoy',
 'frnd',
 'hard',
 'ltd',
 'ni',
 'quiz',
 'identifier',
 'uncle',
 'friday',
 'happened',
 'hit',
 'gone',
 'prob',
 'song',
 'decided',
 'saturday',
 'smth',
 'wonderful',
 'winner',
 'chennai',
 'least',
 'wrong',
 'lovely',
 'wonder',
 'drug',
 'sea',
 'pretty',
 'fri',
 'outside',
 'nope',
 'term',
 'fucking',
 'project',
 'light',
 'read',
 'hold',
 'tel',
 'oredi',
 'goodmorning',
 'darlin',
 'mrng',
 'finally',
 'wit',
 'mu',
 'operator',
 'used',
 'camcorder',
 'crazy',
 'wasn',
 'support',
 'earlier',
 'snow',
 'listen',
 'savamob',
 'frm',
 'cum',
 'ten',
 'jay',
 'fone',
 'blue',
 'unlimited',
 'cd',
 'fr',
 'meant',
 'case',
 'course',
 'log',
 'their',
 'hmm',
 'isn',
 'frnds',
 'whole',
 'telling',
 'seeing',
 'hungry',
 'wq',
 'sunday',
 'freemsg',
 'wkly',
 'father',
 'gas',
 'john',
 'enter',
 'luck',
 'film',
 'na',
 'gn',
 'knew',
 'understand',
 'store',
 'mayb',
 'sell',
 'sex',
 'paper',
 'area',
 'happiness',
 'yar',
 'un',
 'within',
 'park',
 'sk',
 'india',
 'as',
 'rock',
 'couple',
 'talking',
 'motorola',
 'moment',
 'currently',
 'ago',
 'txts',
 'reading',
 'christmas',
 'lost',
 'bslvyl',
 'die',
 'stupid',
 'single',
 'dnt',
 'side',
 'march',
 'balance',
 'mr',
 'hmmm',
 'joy',
 'tired',
 'invited',
 'felt',
 'mah',
 'computer',
 'load',
 'download',
 'hee',
 'cut',
 'move',
 'etc',
 'pas',
 'almost',
 'child',
 'eh',
 'valued',
 'press',
 'difficult',
 'grin',
 'surprise',
 'information',
 'heard',
 'photo',
 'sort',
 'extra',
 'ugh',
 'picking',
 'eye',
 'xy',
 'darren',
 'kid',
 'gym',
 'through',
 'max',
 'redeemed',
 'lady',
 'ipod',
 'doin',
 'supposed',
 'rental',
 'seen',
 'met',
 'ish',
 'figure',
 'via',
 'return',
 'ge',
 'swing',
 'laptop',
 'reveal',
 'bcoz',
 'semester',
 'bill',
 'direct',
 'sending',
 'askd',
 'shower',
 'gotta',
 'complimentary',
 'correct',
 'red',
 'ac',
 'wow',
 'hospital',
 'confirm',
 'charged',
 'promise',
 'comp',
 'police',
 'slowly',
 'loved',
 'fact',
 'fantasy',
 'nobody',
 'truth',
 'asap',
 'whenever',
 'idea',
 'laugh',
 'noon',
 'train',
 'door',
 'clean',
 'blood',
 'member',
 'rent',
 'monday',
 'remove',
 'asking',
 'yep',
 'slow',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'pete',
 'rest',
 'somebody',
 'hmv',
 'leaf',
 'wana',
 'own',
 'lover',
 'road',
 'study',
 'kate',
 'orchard',
 'bath',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'dogging',
 'entered',
 'page',
 'loan',
 'save',
 'rply',
 'checking',
 'joke',
 'crave',
 'abiola',
 'cheer',
 'comin',
 'eg',
 'link',
 'wap',
 'reward',
 'request',
 'usf',
 'std',
 'empty',
 'med',
 'hw',
 'cover',
 'write',
 'bb',
 'ringtones',
 'energy',
 'doctor',
 'convey',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwise',
 'poor',
 'gettin',
 'bag',
 'getzed',
 'summer',
 'wishing',
 'glad',
 'fantastic',
 'gap',
 'king',
 'ho',
 'indian',
 'em',
 'cheap',
 'warm',
 'across',
 'hoping',
 'less',
 'opinion',
 'near',
 'water',
 'different',
 'booked',
 'wc',
 'ldn',
 'voice',
 'mm',
 'mistake',
 'woke',
 'rakhesh',
 'custcare',
 'immediately',
 'merry',
 'normal',
 'somewhere',
 'tonite',
 'usual',
 'deep',
 'admirer',
 'kick',
 'street',
 'teach',
 'deal',
 'bathe',
 'spend',
 'pray',
 'sony',
 'del',
 'men',
 'gave',
 'representative',
 'il',
 'short',
 'forever',
 'situation',
 'reached',
 'oops',
 'catch',
 'turn',
 ...]

In [ ]:
model.corpus_count

5569

In [ ]:
model.epochs

5

In [ ]:
model.wv.similar_by_word('good')

[('wa', 0.9986382722854614),
 ('day', 0.9986003041267395),
 ('about', 0.998552680015564),
 ('all', 0.9985318779945374),
 ('well', 0.9985005259513855),
 ('where', 0.998441219329834),
 ('morning', 0.998411238193512),
 ('not', 0.9984032511711121),
 ('happy', 0.9983976483345032),
 ('my', 0.9983475804328918)]

In [ ]:
model.wv['good'].shape

(100,)

In [ ]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [ ]:
!pip install numpy
import numpy as np
def avg_word2vec(doc):
  return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)

In [ ]:
!pip install tqdm
from tqdm import tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (4.67.3)

In [ ]:
!pip install numpy
X=[]
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)

  7%|▋         | 416/5569 [00:00<00:04, 1070.35it/s]/usr/local/lib/python3.13/dist-packages/numpy/_core/fromnumeric.py:3904: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.13/dist-packages/numpy/_core/_methods.py:147: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:04<00:00, 1295.16it/s]

In [ ]:
X

[array([-1.68096781e-01,  2.67577916e-01,  7.02863708e-02,  1.07870065e-01,
         7.54570663e-02, -5.34875214e-01,  1.36106893e-01,  4.84675735e-01,
        -2.96187520e-01, -9.46510285e-02, -1.66371658e-01, -4.10482377e-01,
        -8.99984225e-05,  8.59468728e-02,  2.18917653e-01, -1.42491356e-01,
         1.38515994e-01, -2.58135378e-01, -4.29444909e-02, -6.08752668e-01,
         2.04019547e-01,  2.00492635e-01,  8.85426551e-02, -1.93648398e-01,
        -7.81559646e-02,  4.00914885e-02, -4.00928527e-01, -2.20771626e-01,
        -2.42332324e-01,  4.14367467e-02,  2.93758601e-01,  5.77434432e-03,
         1.10829078e-01, -2.54516602e-01, -1.15162507e-01,  4.14129287e-01,
        -1.74097915e-03, -1.46078989e-01, -1.22334242e-01, -3.53616267e-01,
         1.40297562e-01, -2.80460328e-01, -1.60945073e-01,  3.21129672e-02,
         2.64044613e-01, -6.99799089e-03, -2.05739349e-01, -5.83969317e-02,
         1.46756828e-01,  1.57540873e-01,  1.77122146e-01, -2.17331469e-01,
        -5.96917905e-02,  7.10631981e-02, -1.00622021e-01,  1.81597412e-01,
         1.78656042e-01,  8.43354315e-02, -2.98559040e-01,  1.59914598e-01,
        -7.96862133e-03,  1.23632170e-01, -6.68859258e-02, -1.29461244e-01,
        -3.48527789e-01,  2.77557045e-01,  8.28175545e-02,  1.88263610e-01,
        -3.54446918e-01,  3.23640019e-01, -2.25858733e-01,  1.22094892e-01,
         3.10271531e-01, -1.82961896e-01,  3.01275700e-01,  1.58072978e-01,
         9.61045828e-03, -1.31110400e-01, -1.77183583e-01,  3.43834832e-02,
        -1.26297012e-01, -1.58320442e-02, -2.24328324e-01,  3.93797249e-01,
        -1.41624674e-01,  3.80897708e-02,  6.33118972e-02,  2.01460138e-01,
         3.94200414e-01, -1.80508029e-02,  2.87873149e-01,  1.30765781e-01,
         2.69129910e-02,  1.45776808e-01,  3.67907584e-01,  3.08235288e-01,
         7.92452618e-02, -1.98259532e-01,  1.42381534e-01, -9.78059396e-02],
       dtype=float32),
 array([-0.1436111 ,  0.23322284,  0.05611077,  0.09930804,  0.06239371,
        -0.47649956,  0.11394807,  0.42841753, -0.25174144, -0.06630182,
        -0.14648257, -0.3561796 , -0.00459187,  0.0663733 ,  0.19415005,
        -0.1345202 ,  0.12616989, -0.22842067, -0.03429642, -0.5297222 ,
         0.18163121,  0.16969484,  0.07347783, -0.16836984, -0.07094502,
         0.0290786 , -0.3541401 , -0.20253885, -0.21280403,  0.03425176,
         0.2575595 ,  0.00606566,  0.09805165, -0.22006823, -0.09828176,
         0.35530728, -0.01577262, -0.12695435, -0.10637709, -0.3185359 ,
         0.12736951, -0.25027847, -0.14520338,  0.03023636,  0.23079342,
        -0.01009357, -0.19066405, -0.0523736 ,  0.13355559,  0.14596301,
         0.15177993, -0.18270878, -0.05583157,  0.07093716, -0.09308172,
         0.16817234,  0.16141745,  0.07503951, -0.26295868,  0.14195211,
        -0.00237681,  0.11322897, -0.06189173, -0.10767923, -0.3071336 ,
         0.24525152,  0.06941275,  0.16913332, -0.31530434,  0.29381883,
        -0.19435757,  0.10541517,  0.2743498 , -0.16287988,  0.26748404,
         0.13409698,  0.00081845, -0.11347073, -0.15639165,  0.02155603,
        -0.10645685, -0.01199424, -0.19930683,  0.34451967, -0.13074066,
         0.03151661,  0.05893846,  0.17948464,  0.33909154, -0.02062153,
         0.2516703 ,  0.11202272,  0.02112976,  0.125308  ,  0.32006985,
         0.26124388,  0.06754389, -0.17726852,  0.11629755, -0.08493447],
       dtype=float32),
 array([-0.16259833,  0.2906451 ,  0.09549037,  0.13593264,  0.08066121,
        -0.5918702 ,  0.13300991,  0.4864482 , -0.31204498, -0.1109217 ,
        -0.18698667, -0.44342774, -0.02190617,  0.07379685,  0.2183242 ,
        -0.15989652,  0.14708868, -0.2908058 , -0.07013562, -0.6219166 ,
         0.17932378,  0.2288695 ,  0.08549364, -0.21853727, -0.05631552,
         0.06699277, -0.42752618, -0.2059951 , -0.23948422,  0.04529333,
         0.28327194,  0.01038499,  0.11634333, -0.24926525, -0.11208039,
         0.45598018,  0.03517347, -0.1937524 , -0.13073407, -0.36691418,
         0.11885253, -0.32045844, -0.18508235,  0.00584923,  0.26373154,
        -0.01641785, -0.21889591, -0.03734627,  0.1599467 ,  0.13848653,
         0.15248877, -0.26926598, -0.03829025,  0.10003285, -0.12405806,
         0.1963411 ,  0.1601777 ,  0.0753993 , -0.3051934 ,  0.1932983 ,
        -0.00279308,  0.10231014, -0.03201455, -0.15114695, -0.35662788,
         0.2818187 ,  0.07333758,  0.2123756 , -0.35426995,  0.35327756,
        -0.27137852,  0.16444315,  0.31732363, -0.22686133,  0.30286866,
         0.18359546,  0.03365195, -0.14213486, -0.1729531 ,  0.00828632,
        -0.11654834, -0.02039901, -0.23339906,  0.40800095, -0.11904754,
         0.04593128,  0.03910428,  0.18297772,  0.40937984,  0.00144062,
         0.28501928,  0.14213252,  0.01199275,  0.14891645,  0.39202318,
         0.2929337 ,  0.05671404, -0.23381323,  0.17741653, -0.1095107 ],
       dtype=float32),
 array([-0.22937475,  0.3575123 ,  0.08689177,  0.14685409,  0.09857897,
        -0.71085346,  0.18318257,  0.6583429 , -0.4002358 , -0.11455303,
        -0.2232765 , -0.54690725,  0.01230324,  0.11509278,  0.29661724,
        -0.19266327,  0.19230929, -0.34932774, -0.04693021, -0.82614714,
         0.286934  ,  0.26727945,  0.11742865, -0.2548391 , -0.10857671,
         0.04773512, -0.53686416, -0.31115872, -0.32387495,  0.05346016,
         0.3949211 ,  0.01269292,  0.14790429, -0.33465576, -0.15365736,
         0.54745275, -0.02504127, -0.18585789, -0.16183959, -0.4804398 ,
         0.20790942, -0.36926648, -0.21312799,  0.05719634,  0.35662913,
        -0.00797261, -0.2790362 , -0.08986748,  0.19906056,  0.21665137,
         0.23437066, -0.2772762 , -0.09143024,  0.09352324, -0.13073376,
         0.24856326,  0.24678208,  0.12076034, -0.39871025,  0.2168567 ,
        -0.00209143,  0.17662813, -0.10086114, -0.15653074, -0.4692408 ,
         0.38282523,  0.10881816,  0.24557473, -0.47933763,  0.43949622,
        -0.29331562,  0.15198253,  0.4183785 , -0.2387558 ,  0.40333945,
         0.19946828,  0.00088417, -0.1723212 , -0.23877208,  0.04415887,
        -0.16521277, -0.01930535, -0.30144042,  0.5273804 , -0.19987914,
         0.0538016 ,  0.10093985,  0.27921313,  0.52576464, -0.03559145,
         0.38755205,  0.16774586,  0.03111521,  0.1974308 ,  0.47931263,
         0.41657946,  0.1089321 , -0.2713196 ,  0.17859478, -0.11734037],
       dtype=float32),
 array([-0.20566998,  0.30255342,  0.08256178,  0.11787385,  0.10108832,
        -0.6057425 ,  0.1486329 ,  0.56331235, -0.3383625 , -0.1088514 ,
        -0.19389288, -0.4683378 ,  0.00304272,  0.09436771,  0.2568142 ,
        -0.16646926,  0.17281349, -0.30475426, -0.04175602, -0.70739675,
         0.24262716,  0.22398834,  0.10124774, -0.21475334, -0.07850245,
         0.04704909, -0.45612857, -0.25268272, -0.27752388,  0.04808838,
         0.3425729 ,  0.0121019 ,  0.12492397, -0.2835995 , -0.13790981,
         0.47038543, -0.00417761, -0.15864219, -0.12149597, -0.40800333,
         0.17803699, -0.32828802, -0.18355893,  0.05351551,  0.29358837,
         0.00285904, -0.2366656 , -0.07936647,  0.15109038,  0.1859297 ,
         0.19236143, -0.24458979, -0.07268617,  0.09180036, -0.11121903,
         0.2141403 ,  0.20467019,  0.10309581, -0.33712867,  0.19247495,
         0.0053027 ,  0.14488916, -0.08430752, -0.12806742, -0.3938941 ,
         0.3158827 ,  0.09292018,  0.20890872, -0.3895292 ,  0.37258402,
        -0.25203565,  0.12967782,  0.35567555, -0.2080415 ,  0.34065557,
         0.15582404, -0.0081774 , -0.14271842, -0.1956092 ,  0.02619316,
        -0.13328116, -0.01047893, -0.25234863,  0.45156756, -0.15728895,
         0.0653721 ,  0.09356283,  0.23173976,  0.44339797, -0.02954836,
         0.3396249 ,  0.1365908 ,  0.02707873,  0.16603166,  0.40553835,
         0.3558191 ,  0.08854877, -0.24508303,  0.15601774, -0.10808156],
       dtype=float32),
 array([-0.2110642 ,  0.32798773,  0.09004515,  0.1343224 ,  0.10091963,
        -0.6580884 ,  0.16070805,  0.5926111 , -0.3614105 , -0.12334727,
        -0.20413713, -0.5047901 , -0.00249047,  0.10807776,  0.26290706,
        -0.17366256,  0.17959557, -0.32376683, -0.05397264, -0.74394375,
         0.2465904 ,  0.24006532,  0.10763323, -0.23982285, -0.07872681,
         0.05674849, -0.48310688, -0.2575869 , -0.28947031,  0.05087968,
         0.3573444 ,  0.00904951,  0.13916117, -0.30331367, -0.1398642 ,
         0.5098161 ,  0.01210603, -0.1816652 , -0.14150773, -0.432224  ,
         0.17026536, -0.35337406, -0.2021905 ,  0.03576514,  0.31359905,
        -0.00660695, -0.25184736, -0.07010064,  0.17305282,  0.18432166,
         0.20505416, -0.27257636, -0.06825756,  0.09306853, -0.12343419,
         0.22886889,  0.21046168,  0.1005074 , -0.35894227,  0.20799667,
        -0.00209416,  0.1409384 , -0.07413431, -0.15021837, -0.42126003,
         0.3351112 ,  0.09558646,  0.22874005, -0.41989943,  0.40289685,
        -0.2819182 ,  0.15064974,  0.37777   , -0.22745807,  0.36637896,
         0.17856   ,  0.00806091, -0.15570533, -0.20258047,  0.02600727,
        -0.14835657, -0.01319793, -0.2708747 ,  0.48086295, -0.16198999,
         0.05719967,  0.08566041,  0.23730747,  0.4824634 , -0.01694133,
         0.35265544,  0.15507221,  0.03091432,  0.17407548,  0.4407995 ,
         0.3724449 ,  0.08791376, -0.25461677,  0.1815992 , -0.11662012],
       dtype=float32),
 array([-2.23176166e-01,  3.42780322e-01,  9.40012112e-02,  1.37105033e-01,
         1.05556861e-01, -6.83267117e-01,  1.68450207e-01,  6.31858826e-01,
        -3.82683694e-01, -1.25364453e-01, -2.11796731e-01, -5.25530159e-01,
         1.14264842e-02,  1.19042791e-01,  2.83142924e-01, -1.82747334e-01,
         1.89616442e-01, -3.34610730e-01, -5.21124490e-02, -7.91970313e-01,
         2.71439672e-01,  2.52310723e-01,  1.15176387e-01, -2.52617061e-01,
        -8.96643400e-02,  5.46522439e-02, -5.12555718e-01, -2.80504018e-01,
        -3.10651004e-01,  5.43981828e-02,  3.80409926e-01,  1.31184673e-02,
         1.49692252e-01, -3.25792462e-01, -1.55011103e-01,  5.37286699e-01,
        -2.77698250e-03, -1.77558646e-01, -1.49694368e-01, -4.60353702e-01,
         1.88289016e-01, -3.64954978e-01, -2.07810372e-01,  4.59058397e-02,
         3.38718563e-01, -5.08675259e-03, -2.66050398e-01, -8.39120597e-02,
         1.81256399e-01,  2.05530077e-01,  2.18827352e-01, -2.72494495e-01,
        -8.72876272e-02,  9.14204940e-02, -1.24912277e-01,  2.40378276e-01,
         2.26570711e-01,  1.09439306e-01, -3.78984928e-01,  2.10149333e-01,
        -7.84200733e-04,  1.59860060e-01, -9.22957212e-02, -1.48178175e-01,
        -4.46097791e-01,  3.59361023e-01,  1.00236014e-01,  2.37850800e-01,
        -4.48151350e-01,  4.19992507e-01, -2.86043227e-01,  1.50855288e-01,
         4.03924704e-01, -2.28222698e-01,  3.87188464e-01,  1.78879976e-01,
         3.80730280e-03, -1.69050485e-01, -2.16224357e-01,  4.08904217e-02,
        -1.61367044e-01, -1.70529746e-02, -2.85673827e-01,  5.10543883e-01,
        -1.80164710e-01,  5.90570047e-02,  9.92726311e-02,  2.61279434e-01,
         5.10208726e-01, -2.12364811e-02,  3.76814902e-01,  1.60705298e-01,
         3.13003547e-02,  1.84321091e-01,  4.63958770e-01,  4.03167814e-01,
         1.00204475e-01, -2.65138447e-01,  1.81905583e-01, -1.24026321e-01],
       dtype=float32),
 array([-0.15588088,  0.2742428 ,  0.0828383 ,  0.11743874,  0.06852531,
        -0.5413988 ,  0.12387996,  0.46573067, -0.2924895 , -0.10604294,
        -0.1646274 , -0.41720727, -0.00314302,  0.08064583,  0.21050371,
        -0.14186378,  0.1373288 , -0.26819837, -0.05331245, -0.59179664,
         0.18535535,  0.20172697,  0.08257643, -0.20186834, -0.06289928,
         0.05958211, -0.39125457, -0.20068054, -0.22711688,  0.03993867,
         0.2782463 ,  0.00530121,  0.1120196 , -0.2387032 , -0.11663098,
         0.4229548 ,  0.02572438, -0.16513233, -0.12320469, -0.34751692,
         0.11800287, -0.28770462, -0.16657072,  0.01277014,  0.24435355,
        -0.00598605, -0.2065796 , -0.04579155,  0.14309354,  0.1419671 ,
         0.16233386, -0.23799445, -0.0525412 ,  0.07303095, -0.09757074,
         0.18185836,  0.14884357,  0.07670025, -0.2870659 ,  0.17081606,
        -0.01629511,  0.10146794, -0.04670246, -0.13741101, -0.3433956 ,
         0.26692924,  0.0675047 ,  0.1804333 , -0.33489224,  0.32967502,
        -0.2350443 ,  0.13992184,  0.29593983, -0.19484186,  0.2901195 ,
         0.16867632,  0.02997264, -0.1403704 , -0.16188109,  0.02439637,
        -0.11536989, -0.01550265, -0.21751694,  0.38888308, -0.12313292,
         0.04237118,  0.04574345,  0.18303487,  0.39483196, -0.00778833,
         0.2787832 ,  0.13129416,  0.02026689,  0.13676801,  0.36026618,
         0.2822227 ,  0.06756379, -0.20791371,  0.1617793 , -0.10163845],
       dtype=float32),
 array([-0.1801124 ,  0.31156912,  0.11570745,  0.14581539,  0.08814023,
        -0.6299626 ,  0.15092638,  0.51549876, -0.32759118, -0.13371514,
        -0.19949535, -0.4755935 , -0.02332802,  0.09023684,  0.23731984,
        -0.16950881,  0.15095602, -0.30844337, -0.08056742, -0.664138  ,
         0.19968149,  0.22898915,  0.09093709, -0.23654464, -0.06899766,
         0.06853759, -0.44554037, -0.21158394, -0.24050193,  0.05244459,
         0.31622913,  0.00227434,  0.12102534, -0.2569498 , -0.13072057,
         0.47207004,  0.04761838, -0.2028948 , -0.13942394, -0.394117  ,
         0.14284225, -0.3428443 , -0.18338263,  0.01644993,  0.27512878,
        -0.00951277, -0.22829096, -0.04317992,  0.16589868,  0.14074457,
         0.18510936, -0.29724473, -0.04657133,  0.09925226, -0.12915285,
         0.20835738,  0.17758651,  0.08579856, -0.32651535,  0.20778927,
        -0.01921908,  0.10343299, -0.04481825, -0.1654615 , -0.38458833,
         0.29812723,  0.08738498,  0.21147977, -0.37361184,  0.379132  ,
        -0.2897626 ,  0.16522308,  0.33025494, -0.2349377 ,  0.3184324 ,
         0.19038397,  0.04703995, -0.15335982, -0.18218116,  0.0107796 ,
        -0.13322884, -0.01503088, -0.24863537,  0.43481913, -0.11417776,
         0.06009213,  0.04290561,  0.18986158,  0.4373423 , -0.01550088,
         0.30802903,  0.13953014,  0.00377159,  0.13723686,  0.4219323 ,
         0.3020059 ,  0.0528439 , -0.25474295,  0.19351344, -0.1016672 ],
       dtype=float32),
 array([-0.19653012,  0.36553508,  0.12518027,  0.17567451,  0.09579429,
        -0.73665696,  0.15773372,  0.59949696, -0.38490033, -0.14287701,
        -0.23532866, -0.55872136, -0.03068   ,  0.09485624,  0.27666566,
        -0.19501099,  0.17409448, -0.36272088, -0.08578747, -0.7638931 ,
         0.2148182 ,  0.28183758,  0.10566168, -0.2748161 , -0.06384675,
         0.08520883, -0.52647024, -0.24439877, -0.2914369 ,  0.05737435,
         0.35082227,  0.00274423,  0.14544608, -0.30113912, -0.14290695,
         0.5681935 ,  0.05848882, -0.25098187, -0.17042822, -0.45259544,
         0.13952564, -0.39684543, -0.23253103, -0.00344552,  0.3207316 ,
        -0.01831487, -0.27747905, -0.04206485,  0.2020571 ,  0.16835935,
         0.19492474, -0.34805036, -0.04259172,  0.11464987, -0.14923027,
         0.24156857,  0.18676287,  0.0920196 , -0.37089264,  0.24036585,
        -0.01176006,  0.11561733, -0.03303521, -0.19249195, -0.44902122,
         0.3487278 ,  0.0917907 ,  0.26129353, -0.4404969 ,  0.44961762,
        -0.33265832,  0.21219201,  0.3905499 , -0.28647292,  0.3732127 ,
         0.24554901,  0.05868487, -0.18452643, -0.21342936,  0.01774039,
        -0.14763045, -0.02457205, -0.29274952,  0.51427686, -0.1453288 ,
         0.04981909,  0.03556052,  0.22095864,  0.51657546,  0.00345527,
         0.35792762,  0.18113333,  0.015353  ,  0.17960012,  0.49762845,
         0.35391888,  0.06794493, -0.28346288,  0.2203045 , -0.13801807],
       dtype=float32),
 array([-0.21149561,  0.3143686 ,  0.08353808,  0.12231977,  0.10170358,
        -0.63173866,  0.15161274,  0.5820499 , -0.3438458 , -0.1182786 ,
        -0.19811785, -0.4854875 ,  0.00462319,  0.10429344,  0.26089233,
        -0.1737963 ,  0.17711508, -0.31577957, -0.0484456 , -0.7284457 ,
         0.24877408,  0.2298915 ,  0.09981767, -0.229338  , -0.0814165 ,
         0.05267072, -0.46608317, -0.25284824, -0.27906632,  0.05299281,
         0.35110754,  0.01091557,  0.13125566, -0.29344615, -0.14098074,
         0.48964685,  0.00730524, -0.16987151, -0.12825386, -0.41918683,
         0.17406237, -0.34158778, -0.19264518,  0.04336036,  0.3025079 ,
        -0.00103112, -0.23811613, -0.07721656,  0.16180371,  0.18552716,
         0.20198664, -0.2565314 , -0.071478  ,  0.09394006, -0.11283406,
         0.22414787,  0.21174392,  0.09844484, -0.34551787,  0.19794832,
         0.0016264 ,  0.1413716 , -0.08024091, -0.13776797, -0.40680647,
         0.32610986,  0.0968538 ,  0.21605259, -0.4041204 ,  0.38560715,
        -0.26774165,  0.13441947,  0.370064  , -0.21110639,  0.3520079 ,
         0.16996475,  0.00095369, -0.14837712, -0.19835413,  0.02829849,
        -0.1434259 , -0.01114679, -0.260161  ,  0.46709773, -0.15727918,
         0.06083446,  0.08807379,  0.23623686,  0.468194  , -0.02028823,
         0.3496578 ,  0.14406459,  0.03198324,  0.16668329,  0.42545247,
         0.36700797,  0.0883645 , -0.24811593,  0.16903795, -0.11151061],
       dtype=float32),
 array([-0.20372665,  0.33945978,  0.11235453,  0.15733749,  0.10486495,
        -0.6985748 ,  0.1571825 ,  0.57585824, -0.36910337, -0.13140965,
        -0.22111908, -0.5222963 , -0.01827314,  0.09332455,  0.26249775,
        -0.19040173,  0.1809786 , -0.34288484, -0.0874293 , -0.7396859 ,
         0.21795535,  0.26720935,  0.09909949, -0.2580615 , -0.06355291,
         0.07538934, -0.49765104, -0.24240279, -0.2845028 ,  0.05695421,
         0.34114957,  0.01071053,  0.13659512, -0.29295743, -0.13806264,
         0.5348952 ,  0.03909767, -0.2268909 , -0.15113616, -0.43648693,
         0.14738096, -0.378425  , -0.21006148,  0.01098216,  0.30777988,
        -0.01586368, -0.2612382 , -0.04751946,  0.1819926 ,  0.1623818 ,
         0.18680054, -0.31589556, -0.04818544,  0.11365645, -0.14442068,
         0.22952183,  0.1970476 ,  0.09331669, -0.36137843,  0.2302601 ,
        -0.00459499,  0.12238121, -0.04441318, -0.17540589, -0.42207834,
         0.3312614 ,  0.08986741,  0.24813634, -0.41685188,  0.41931945,
        -0.31702387,  0.18387803,  0.36973283, -0.2647499 ,  0.3537877 ,
         0.20388216,  0.04071004, -0.1616878 , -0.2067152 ,  0.0058133 ,
        -0.13994828, -0.02173141, -0.27447572,  0.48158488, -0.13589069,
         0.06198729,  0.05182143,  0.21725492,  0.48299947, -0.00586932,
         0.34306377,  0.16605432,  0.0118323 ,  0.17452107,  0.45648065,
         0.34800252,  0.06963956, -0.28323916,  0.21301845, -0.12563308],
       dtype=float32),
 array([-0.21403947,  0.3595658 ,  0.12671183,  0.16398977,  0.10561249,
        -0.72722936,  0.17041546,  0.5959986 , -0.38172045, -0.14283542,
        -0.22962339, -0.5508876 , -0.02637971,  0.09537697,  0.2767685 ,
        -0.19025148,  0.18165141, -0.35979614, -0.08713752, -0.7670562 ,
         0.22066216,  0.27694643,  0.10447674, -0.27384385, -0.07137828,
         0.0831663 , -0.51936996, -0.24777591, -0.28589338,  0.06029966,
         0.36457548,  0.00158621,  0.14101338, -0.3012378 , -0.14535503,
         0.55395365,  0.05213187, -0.23435181, -0.15237255, -0.4586115 ,
         0.1612608 , -0.40237752, -0.21995251,  0.01436058,  0.3205617 ,
        -0.01178974, -0.26970077, -0.04902438,  0.19041948,  0.16216035,
         0.20527616, -0.34037447, -0.04972447,  0.11520962, -0.15201852,
         0.24279115,  0.20841895,  0.09623571, -0.38193187,  0.2389222 ,
        -0.0134145 ,  0.12054815, -0.03816726, -0.1850151 , -0.44622767,
         0.34352112,  0.09509435,  0.2521015 , -0.43142942,  0.43464476,
        -0.3343462 ,  0.19047979,  0.38867882, -0.27301738,  0.36896402,
         0.21880278,  0.04628827, -0.1733878 , -0.21499208,  0.00987989,
        -0.1472028 , -0.01986964, -0.2842913 ,  0.5068514 , -0.13374873,

In [ ]:
X_new=np.array(X)

In [ ]:
len(X)

5569

In [ ]:
X_new.shape

(5569,)

In [ ]:
y=messages[list(map(lambda x: len(x)>0,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values    #Dependent Features

In [ ]:
messages.shape

(5572, 2)

In [ ]:
y.shape

(5569,)

In [ ]:
df=pd.DataFrame()
for i in range(0,len(X)):
  df = pd.concat(
        [df, pd.DataFrame(X[i].reshape(1, -1))],
        ignore_index=True
    )

/tmp/ipykernel_472/1205082906.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.168097,0.267578,0.070286,0.107870,0.075457,-0.534875,0.136107,0.484676,-0.296188,-0.094651,...,0.287873,0.130766,0.026913,0.145777,0.367908,0.308235,0.079245,-0.198260,0.142382,-0.097806
1,-0.143611,0.233223,0.056111,0.099308,0.062394,-0.476500,0.113948,0.428418,-0.251741,-0.066302,...,0.251670,0.112023,0.021130,0.125308,0.320070,0.261244,0.067544,-0.177269,0.116298,-0.084934
2,-0.162598,0.290645,0.095490,0.135933,0.080661,-0.591870,0.133010,0.486448,-0.312045,-0.110922,...,0.285019,0.142133,0.011993,0.148916,0.392023,0.292934,0.056714,-0.233813,0.177417,-0.109511
3,-0.229375,0.357512,0.086892,0.146854,0.098579,-0.710853,0.183183,0.658343,-0.400236,-0.114553,...,0.387552,0.167746,0.031115,0.197431,0.479313,0.416579,0.108932,-0.271320,0.178595,-0.117340
4,-0.205670,0.302553,0.082562,0.117874,0.101088,-0.605743,0.148633,0.563312,-0.338362,-0.108851,...,0.339625,0.136591,0.027079,0.166032,0.405538,0.355819,0.088549,-0.245083,0.156018,-0.108082

In [ ]:
df['Output']=y

In [ ]:
df.dropna(inplace=True)

In [ ]:
X=df

In [ ]:
X.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [ ]:
y=df['Output']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
y_train

1828     True
3728     True
625      True
2253     True
501      True
        ...
4941     True
3268     True
1655     True
2611    False
2736     True
Name: Output, Length: 4445, dtype: bool

In [ ]:


X_train.columns = X_train.columns.astype(str)
X_test.columns = X_test.columns.astype(str)

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(random_state=42)
classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

1.0

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00       157
        True       1.00      1.00      1.00       955

    accuracy                           1.00      1112
   macro avg       1.00      1.00      1.00      1112
weighted avg       1.00      1.00      1.00      1112